[versions]
# libraries
gson = "2.11.0"
sentrysdk = "8.26.0"
annotations = "26.0.1"

# test libraries
junit = "5.10.2"
junitplatform = "1.9.2"
junit4 = "4.13.2"
assertj = "3.27.0"
mockito = "5.2.0"

# plugins
gradleIntelliJPlugin = "2.10.4"
semver = "1.0.4"
asciidoc = "5.0.0-alpha.1"
kotlin = "2.1.20"

[libraries]
gson = { group = "com.google.code.gson", name= "gson",  version.ref = "gson" }
sentrysdk = { group = "io.sentry", name="sentry", version.ref = "sentrysdk" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# test libraries
junit = { group = "org.junit.jupiter", name= "junit-jupiter",  version.ref = "junit" }
junitengine = { group = "org.junit.jupiter", name= "junit-jupiter-engine",  version.ref = "junit" }
junitplatform = { group = "org.junit.platform", name= "junit-platform-launcher",  version.ref = "junitplatform" }
junit4 = { group = "junit", name="junit", version.ref="junit4"}
assertj = { group = "org.assertj", name= "assertj-core", version.ref = "assertj" }
mockito = { group = "org.mockito", name="mockito-core", version.ref = "mockito" }

[plugins]
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
semver = { id="net.thauvin.erik.gradle.semver" , version.ref="semver"}
asciidoc = {id="org.asciidoctor.jvm", version.ref="asciidoc"}
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
