[versions]
# libraries
okhttp = "4.12.0"
sentrysdk = "8.5.0"
annotations = "26.0.1"
lsp-library = "0.2.14"


# test libraries
junit = "5.10.2"
junitplatform = "1.9.2"
junit4 = "4.13.2"
opentest4j = "1.3.0"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.5.0"
kotlin = "2.1.20"
kover = "0.9.1"
qodana = "2024.3.4"
devjaidelsp = "0.3.2"

[libraries]
sentrysdk = { group = "io.sentry", name="sentry", version.ref = "sentrysdk" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
lsp-client = "dev.j-a.ide:lsp-client:default"

# test libraries
junit = { group = "org.junit.jupiter", name= "junit-jupiter",  version.ref = "junit" }
junitengine = { group = "org.junit.jupiter", name= "junit-jupiter-engine",  version.ref = "junit" }
junitplatform = { group = "org.junit.platform", name= "junit-platform-launcher",  version.ref = "junitplatform" }
junit4 = { group = "junit", name="junit", version.ref="junit4"}

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
devjaidelsp = {id ="dev.j-a.ide.lsp", version.ref="devjaidelsp" }
